//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OX3DGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OX3DGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 150
        ///
        ///in vec4 inPosition;
        ///in vec4 inNormal;
        ///
        ///uniform mat4 mvpMatrix;
        ///uniform mat4 normalMatrix;
        ///uniform mat4 mvMatrix;
        ///uniform vec3 lightPositions[5];
        ///uniform vec3 objectColor;
        ///uniform vec3 lightColorsDiff[5];
        ///uniform vec3 lightColorsSpec[5];
        ///uniform float shininess;
        ///uniform float ambientStrength;
        ///uniform vec3 spotLightPosition;
        ///uniform vec3 spotLightColorDiff;
        ///uniform vec3 spotLightColorSpec;
        ///uniform vec3 spotLightVector;
        ///uniform float spotLightFocus;
        ///
        ///smooth out vec3 Color;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gouraud_Blinn_vert {
            get {
                return ResourceManager.GetString("Gouraud_Blinn_vert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 150
        ///
        ///in vec4 inPosition;
        ///in vec4 inNormal;
        ///
        ///uniform mat4 mvpMatrix;
        ///uniform mat4 normalMatrix;
        ///uniform mat4 mvMatrix;
        ///uniform vec3 lightPositions[5];
        ///uniform vec3 objectColor;
        ///uniform vec3 lightColorsDiff[5];
        ///uniform vec3 lightColorsSpec[5];
        ///uniform float shininess;
        ///uniform float ambientStrength;
        ///uniform vec3 spotLightPosition;
        ///uniform vec3 spotLightColorDiff;
        ///uniform vec3 spotLightColorSpec;
        ///uniform vec3 spotLightVector;
        ///uniform float spotLightFocus;
        ///
        ///smooth out vec3 Color;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gouraud_Phong_vert {
            get {
                return ResourceManager.GetString("Gouraud_Phong_vert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 150
        ///
        ///smooth in vec3 Normal;
        ///smooth in vec3 Position;
        ///
        ///uniform vec3 lightPositions[5];
        ///uniform vec3 objectColor;
        ///uniform vec3 lightColorsDiff[5];
        ///uniform vec3 lightColorsSpec[5];
        ///uniform float shininess;
        ///uniform float ambientStrength;
        ///uniform vec3 spotLightPosition;
        ///uniform vec3 spotLightColorDiff;
        ///uniform vec3 spotLightColorSpec;
        ///uniform vec3 spotLightVector;
        ///uniform float spotLightFocus;
        ///
        ///out vec3 Color;
        ///
        ///void main() {
        ///
        ///	Color = objectColor * ambientStrength;
        ///	vec3 vNormal =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phong_Blinn_frag {
            get {
                return ResourceManager.GetString("Phong_Blinn_frag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 150
        ///
        ///smooth in vec3 Normal;
        ///smooth in vec3 Position;
        ///
        ///uniform vec3 lightPositions[5];
        ///uniform vec3 objectColor;
        ///uniform vec3 lightColorsDiff[5];
        ///uniform vec3 lightColorsSpec[5];
        ///uniform float shininess;
        ///uniform float ambientStrength;
        ///uniform vec3 spotLightPosition;
        ///uniform vec3 spotLightColorDiff;
        ///uniform vec3 spotLightColorSpec;
        ///uniform vec3 spotLightVector;
        ///uniform float spotLightFocus;
        ///
        ///out vec3 Color;
        ///
        ///void main() {
        ///
        ///	Color = objectColor * ambientStrength;
        ///	vec3 vNormal =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phong_Phong_frag {
            get {
                return ResourceManager.GetString("Phong_Phong_frag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 150
        ///
        ///smooth in vec3 Color;
        ///
        ///out vec3 out_color;
        ///
        ///void main() {
        ///out_color = Color.rgb;
        ///}.
        /// </summary>
        internal static string Simple_frag {
            get {
                return ResourceManager.GetString("Simple_frag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 150
        ///
        ///in vec4 inPosition;
        ///in vec4 inNormal;
        ///
        ///uniform mat4 mvpMatrix;
        ///uniform mat4 normalMatrix;
        ///uniform mat4 mvMatrix;
        ///
        ///smooth out vec3 Normal;
        ///smooth out vec3 Position;
        ///
        ///
        ///void main() {
        ///
        ///	gl_Position = mvpMatrix * inPosition;
        ///	Normal = normalize((normalMatrix * inNormal).xyz);
        ///
        ///	vec4 vEyePosition = mvMatrix * inPosition;
        ///	Position = vEyePosition.xyz / vEyePosition.w;
        ///}.
        /// </summary>
        internal static string Simple_vert {
            get {
                return ResourceManager.GetString("Simple_vert", resourceCulture);
            }
        }
    }
}
